- hosts: localhost
  vars:
      version: "{{ lookup('file', 'version.txt') }}"
  tasks:
  - name: Create index file using Jinja2 template
    template:
      src: index.j2
      dest: index.html
  - name: Simple PUT operation
    amazon.aws.aws_s3:
      bucket: mapfre-gitops-rauflint
      object: /index.html
      src: index.html
      mode: put